### ISSUE TITLE
Possible digitization mistake

### ISSUE THREAD

**Issue by jcuenod** [openscriptures/GreekResources#1]
I could be wrong but shouldn't "βουλόλιον" be "βουκόλιον" (both key and lemma)? I think this mistake originates in the CCAT data.

https://github.com/openscriptures/GreekResources/blob/f999862aba446ad5632c1c38d16bf9c168b87cfb/LxxLemmas/Eccl.js#L481

**Comment by DavidTroidl** [comment]
The correction has been made. Thanks.
